### ISSUE TITLE
Support subset needed by Moshi

### ISSUE THREAD

**Issue by yogurtearl** [Kotlin/kotlinx.reflect.lite#14]
If `kotlinx.reflect.lite` could support the subset needed by Moshi, could make Moshi with reflection a more viable option.

https://github.com/square/moshi/blob/master/kotlin/reflect/src/main/java/com/squareup/moshi/kotlin/reflect/KotlinJsonAdapter.kt

```kotlin
import kotlin.reflect.full.findAnnotation
import kotlin.reflect.full.memberProperties
import kotlin.reflect.full.primaryConstructor
import kotlin.reflect.jvm.isAccessible
import kotlin.reflect.jvm.javaField
import kotlin.reflect.jvm.javaType
```

**Comment by rodion-m** [comment]
It's really needed.

**Comment by ZacSweers** [comment]
It would be fantastic if `typeOf()` could be safely supported with this as well!

**Comment by udalov** [comment]
@ZacSweers I wonder what exactly kind of support do you mean? `typeOf` is a standard library feature and doesn't require any Kotlin reflection implementation.

**Comment by ZacSweers** [comment]
Sorry I should have elaborated more :).

`typeOf()` is supported, but I guess what I really mean is supporting more of `KType`. `KType` itself is in stdlib, but accessing _any_ of its properties requires kotlin-reflect. I see there's a `TypeReference` implementation of it in the stdlib, but is apparently not targeting production use until Kotlin 1.4

Example of how we use it in moshi's reflection artifact: https://github.com/square/moshi/pull/875

**Comment by ZacSweers** [comment]
I think this could be closed, I've opened a PR in Moshi to remove kotlin-reflect entirely and replace it with kotlinx-metadata: https://github.com/square/moshi/pull/1076

Fuller KType support in kotlinx.reflect.lite would still be great though!
