### ISSUE TITLE
Duplicate class a.a.a.c.a found in kotlinx.reflect.lite-1.0.0.jar

### ISSUE THREAD

**Issue by SaqibJDev** [Kotlin/kotlinx.reflect.lite#16]
Hi, 
I'm facing this exception with one of my dependency provided by a vendor. Is there a way to fix this? 

`Duplicate class a.a.a.c.a found in kotlinx.reflect.lite-1.0.0.jar`

**Comment by baruchn** [comment]
Same here. Looks like this library is missing proguard rules.

**Comment by qwwdfsad** [comment]
We are reworking it right now and will take care of proguard rules separately, for now closing as "the current code is no longer supported"
