### ISSUE TITLE
1.0.0 beta release please

### ISSUE THREAD

**Issue by apatrida** [Kotlin/kotlinx.reflect.lite#5]
to prepare for M15 is good to also have a snapshot build off of 0.1-SNAPSHOT of Kotlin

**Comment by apatrida** [comment]
ok, push `1.0.0-beta-1038` release to bintray instead?

**Comment by apatrida** [comment]
when @udalov is done with changes that it looks like he started (or finished) for 1.0.0-beta-1038 can @orangy or @udalov push to bintray?

**Comment by udalov** [comment]
1.0.0-beta-1038 pushed to bintray
